# Generated by Django 3.0.4 on 2020-04-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='DATREF',
        ),
    ]
