# Generated by Django 3.0.4 on 2020-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0002_remove_dadosmestre_verba_datref'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='DATREF',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
