# Generated by Django 3.0.4 on 2020-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0003_dadosmestre_verba_datref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='DATREF',
            field=models.DateField(blank=True, null=True),
        ),
    ]
