# Generated by Django 3.0.4 on 2020-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0004_auto_20200407_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='DATREF',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
