# Generated by Django 3.0.4 on 2020-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0005_auto_20200407_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CODREGPCO',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
