# Generated by Django 3.0.4 on 2020-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0006_auto_20200407_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='TIPCALUTZPCOLIQ',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
