# Generated by Django 3.0.4 on 2020-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0008_auto_20200407_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CODREGPCO',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='DATREF',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
