# Generated by Django 3.0.4 on 2020-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0009_auto_20200407_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretrizesEstrategica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODESTUNI', models.CharField(max_length=2)),
                ('CODDIVFRN', models.IntegerField()),
                ('DATREFPOD', models.DateTimeField(blank=True, null=True)),
                ('NOMMES', models.DateTimeField(blank=True, null=True)),
                ('NOMSMS', models.DateTimeField(blank=True, null=True)),
                ('NOMDIASMN', models.DateTimeField(blank=True, null=True)),
                ('NOMSMSANO', models.DateTimeField(blank=True, null=True)),
                ('CODCLLCMPATU', models.IntegerField()),
                ('DESCLLCMPATU', models.CharField(blank=True, max_length=50, null=True)),
                ('DESDRTCLLATU', models.CharField(max_length=150)),
                ('VLRVNDFATLIQ', models.CharField(max_length=45)),
                ('VLRRCTLIQAPU', models.CharField(max_length=45)),
                ('VLRMRGCRB', models.CharField(max_length=45)),
                ('VLRMRGBRT', models.CharField(max_length=45)),
                ('NOMCPR', models.CharField(max_length=45)),
                ('CODFIL', models.IntegerField(blank=True, null=True)),
                ('CODGRPMER', models.IntegerField(blank=True, null=True)),
                ('DESGRPMER', models.CharField(max_length=45)),
                ('CODFMLMER', models.IntegerField(blank=True, null=True)),
                ('DESFMLMER', models.CharField(max_length=45)),
                ('CODCLSMER', models.IntegerField(blank=True, null=True)),
                ('DESCLSMER', models.CharField(max_length=45)),
                ('CODDRTCLLATU', models.IntegerField()),
                ('NOMGRPFRN', models.CharField(max_length=150)),
                ('NOMFRN', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'mrt.CADDTZETT',
            },
        ),
    ]
