# Generated by Django 3.0.4 on 2020-04-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0010_diretrizesestrategica'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='INDCTGTOP',
            field=models.TextField(blank=True, null=True),
        ),
    ]
