# Generated by Django 3.0.4 on 2020-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0012_auto_20200407_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='DATREFPOD',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMDIASMN',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMMES',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMSMS',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMSMSANO',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
