# Generated by Django 3.0.4 on 2020-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0014_planocomprasviewset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODESTUNI', models.CharField(max_length=2)),
                ('CODFILEPD', models.IntegerField()),
                ('CODFILFAT', models.IntegerField()),
                ('CODPRD', models.IntegerField()),
                ('NUMANOMESSMN', models.CharField(max_length=50)),
                ('MRGBRTOCD', models.TextField()),
                ('VLRRCTLIQCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRCSTCMPMER', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRCSTCMPIDL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRCMVOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRCMVCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRFLXPLN', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRFLXSUG', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRICMOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRICMCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRIMPTOTOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRIMPTOTCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRMRGBRTOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRMRGBRTCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRPCOBSECAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRPCOBSEOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRMCDOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRMCDCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRDVLCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRPISOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRPISCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRPCOMEDMCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRVNDLIQOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRVNDLIQCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRVNDPRVCTR', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRPCOVNDLIQOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRPCOVNDLIQCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRVBAOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRRBTCAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VLRRBTOCD', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'mrt.MOVPLNCMPCAL',
            },
        ),
        migrations.DeleteModel(
            name='PlanoComprasViewSet',
        ),
    ]
