# Generated by Django 3.0.4 on 2020-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0015_auto_20200409_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocompras',
            name='vlrcmvpcoatu',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
