# Generated by Django 3.0.4 on 2020-04-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0016_planocompras_vlrcmvpcoatu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planocompras',
            old_name='vlrcmvpcoatu',
            new_name='VLRCMVCOATU',
        ),
    ]
