# Generated by Django 3.0.4 on 2020-04-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0017_auto_20200409_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planocompras',
            old_name='VLRCMVCOATU',
            new_name='VLRCMVPCOATU',
        ),
    ]
