# Generated by Django 3.0.4 on 2020-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0018_auto_20200409_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocompras',
            name='VLRRCTLIQOCD',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planocompras',
            name='MRGBRTOCD',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
