# Generated by Django 3.0.4 on 2020-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0019_auto_20200409_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planocompras',
            name='VLRRCTLIQCAL',
        ),
        migrations.AddField(
            model_name='planocompras',
            name='VLRDVLOCD',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='competitividade',
            name='CODIDTCUR',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
