# Generated by Django 3.0.4 on 2020-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0020_auto_20200410_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitividade',
            name='CODIDTCUR',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]

