# Generated by Django 3.0.4 on 2020-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0021_auto_20200410_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitividade',
            name='VLRPCOMEDMCD',
            field=models.CharField(max_length=15),
        ),
    ]
