# Generated by Django 3.0.4 on 2020-04-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0022_auto_20200410_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitividade',
            name='DATREF',
        ),
        migrations.RemoveField(
            model_name='competitividade',
            name='NOMMES',
        ),
        migrations.RemoveField(
            model_name='competitividade',
            name='NUMANO',
        ),
        migrations.RemoveField(
            model_name='competitividade',
            name='NUMANOMES',
        ),
        migrations.RemoveField(
            model_name='competitividade',
            name='NUMSMNANO',
        ),
    ]
