# Generated by Django 3.0.4 on 2020-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0023_auto_20200410_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitividade',
            name='DATREF',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='competitividade',
            name='NOMMES',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='competitividade',
            name='NUMANO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitividade',
            name='NUMANOMES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitividade',
            name='NUMSMNANO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
