# Generated by Django 3.0.4 on 2020-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0024_auto_20200410_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitividade',
            name='CLFCRVABCMER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
