# Generated by Django 3.0.4 on 2020-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_parsing', '0025_auto_20200410_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitividade',
            name='CLFCRVABCMER',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='competitividade',
            name='CODESTUNI',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
