# Generated by Django 3.0.3 on 2020-03-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAMADA',
            fields=[
                ('Cod_Camada', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nome_Camada', models.CharField(max_length=50)),
                ('TIPO_BASE_VENDAS', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CHAVE_CONTAS',
            fields=[
                ('Cod_ChaveContas', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Desc_ChaveContas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CONDICAO',
            fields=[
                ('Cod_Condicao', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Desc_Condicao', models.CharField(max_length=50)),
                ('Escala_Qtde', models.IntegerField()),
                ('POS_NEG', models.CharField(max_length=1)),
                ('TIP_BASE_VENDAS', models.CharField(max_length=1)),
                ('MANDATORIA', models.IntegerField()),
                ('ESTATISTICA', models.IntegerField()),
                ('Cod_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CAMADA')),
                ('Cod_ChaveContas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CHAVE_CONTAS')),
            ],
        ),
        migrations.CreateModel(
            name='ESQUEMA_DE_CALCULO',
            fields=[
                ('Cod_Esquema_Calculo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TIP_BASE_VENDAS', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ESTADO',
            fields=[
                ('Cod_Estado', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Desc_Estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FATURAMENTO',
            fields=[
                ('Cod_Faturamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Desc_Faturamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FILIAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Filial', models.IntegerField()),
                ('Desc_Filial', models.CharField(max_length=50)),
                ('Cod_Faturamento', models.CharField(max_length=10)),
                ('Cod_Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESTADO')),
            ],
        ),
        migrations.CreateModel(
            name='MERCADORIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESTIPCRT', models.CharField(max_length=3)),
                ('CODPRD', models.CharField(max_length=10)),
                ('DESPRD', models.CharField(max_length=50)),
                ('CODGRPPRD', models.CharField(max_length=10)),
                ('CODCLSPRD', models.CharField(max_length=10)),
                ('DESCLSPRD', models.CharField(max_length=50)),
                ('CODSUBCTGPRD', models.CharField(max_length=5)),
                ('DESSUBCTGPRD', models.CharField(max_length=50)),
                ('CODSMR', models.IntegerField()),
                ('DESSMR', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SEQ_CAMPO',
            fields=[
                ('Cod_Campo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nome_Campo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEQUENCIA',
            fields=[
                ('Cod_Sequencia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nome_Sequencia', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TIPOVALOR',
            fields=[
                ('Cod_TipoValor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Desc_TipoValor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SEQ_AUX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQ_CAMPO')),
                ('Cod_Sequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQUENCIA')),
            ],
        ),
        migrations.CreateModel(
            name='REGION',
            fields=[
                ('Cod_Region', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Tipo_Region', models.CharField(max_length=50)),
                ('Cod_Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESTADO')),
            ],
        ),
        migrations.CreateModel(
            name='PRECO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chave', models.IntegerField()),
                ('Data', models.DateTimeField()),
                ('Valor', models.FloatField()),
                ('Tipo_Base_Venda', models.CharField(max_length=1)),
                ('Cod_Esquema_Calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESQUEMA_DE_CALCULO')),
            ],
        ),
        migrations.CreateModel(
            name='FILIAL_MERCADORIA',
            fields=[
                ('Cod_Filial_Mercadoria', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tipo_Region', models.IntegerField()),
                ('Cod_Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESTADO')),
                ('Cod_Faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.FATURAMENTO')),
                ('Cod_Filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.FILIAL')),
                ('Cod_Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.REGION')),
                ('id_Mercadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.MERCADORIA')),
            ],
        ),
        migrations.AddField(
            model_name='faturamento',
            name='Cod_Filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.FILIAL'),
        ),
        migrations.CreateModel(
            name='ESQUEMA_FILIAL_MERCADORIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Esquema_Calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESQUEMA_DE_CALCULO')),
                ('Cod_Filial_Mercadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.FILIAL_MERCADORIA')),
            ],
        ),
        migrations.CreateModel(
            name='CONDICAO_SEQUENCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO')),
                ('Cod_Sequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQUENCIA')),
            ],
        ),
        migrations.CreateModel(
            name='CONDICAO_CAMADA_ESQUEMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CAMADA')),
                ('Cod_Condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO')),
                ('Cod_Esquema_Calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESQUEMA_DE_CALCULO')),
            ],
        ),
        migrations.AddField(
            model_name='condicao',
            name='Cod_TipoValor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.TIPOVALOR'),
        ),
    ]
