# Generated by Django 3.0.4 on 2020-03-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAMADA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Camada', models.CharField(max_length=10, unique=True)),
                ('Nome_Camada', models.CharField(max_length=50)),
                ('TIPO_BASE_VENDAS', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CANAL_VENDAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Vendas', models.CharField(max_length=10)),
                ('Desc_Vendas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CHAVE_CONTAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_ChaveContas', models.CharField(max_length=10, unique=True)),
                ('Desc_ChaveContas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CONDICAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Condicao', models.CharField(max_length=10, unique=True)),
                ('Desc_Condicao', models.CharField(max_length=50)),
                ('Escala_Qtde', models.IntegerField()),
                ('POS_NEG', models.CharField(max_length=1)),
                ('TIP_BASE_VENDAS', models.CharField(max_length=1)),
                ('MANDATORIA', models.IntegerField()),
                ('ESTATISTICA', models.IntegerField()),
                ('id_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CAMADA')),
                ('id_ChaveContas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CHAVE_CONTAS')),
            ],
        ),
        migrations.CreateModel(
            name='ESQUEMA_DE_CALCULO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_CanalVendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CANAL_VENDAS')),
            ],
        ),
        migrations.CreateModel(
            name='LINHA_NEGOCIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_LinhaNegocio', models.CharField(max_length=10)),
                ('Desc_LinhaNegocio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SEQ_CAMPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Campo', models.CharField(max_length=10, unique=True)),
                ('Nome_Campo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEQUENCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Sequencia', models.CharField(max_length=10, unique=True)),
                ('Nome_Sequencia', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TIPOVALOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_TipoValor', models.CharField(max_length=10, unique=True)),
                ('Desc_TipoValor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SEQ_AUX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQ_CAMPO')),
                ('id_Sequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQUENCIA')),
            ],
        ),
        migrations.CreateModel(
            name='PRECO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chave', models.IntegerField()),
                ('Data', models.DateTimeField()),
                ('Valor', models.FloatField()),
                ('Tipo_Base_Venda', models.CharField(max_length=1)),
                ('id_Esquema_Calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESQUEMA_DE_CALCULO')),
            ],
        ),
        migrations.AddField(
            model_name='esquema_de_calculo',
            name='id_LinhaNegocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.LINHA_NEGOCIO'),
        ),
        migrations.CreateModel(
            name='CONDICAO_SEQUENCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO')),
                ('id_Sequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQUENCIA')),
            ],
        ),
        migrations.CreateModel(
            name='CONDICAO_CAMADA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CAMADA')),
                ('id_Condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO')),
            ],
        ),
        migrations.AddField(
            model_name='condicao',
            name='id_TipoValor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.TIPOVALOR'),
        ),
        migrations.CreateModel(
            name='CAMADA_ESQUEMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Condicao_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO_CAMADA')),
                ('id_Esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESQUEMA_DE_CALCULO')),
            ],
        ),
    ]
