# Generated by Django 3.0.3 on 2020-03-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEQ_CAMPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Campo', models.CharField(max_length=10, unique=True)),
                ('Nome_Campo', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
