# Generated by Django 3.0.3 on 2020-03-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicao',
            name='Cod_Camada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAMADA', to='dinamica.CAMADA'),
        ),
    ]
