# Generated by Django 3.0.3 on 2020-03-07 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0002_sequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEQ_AUX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQ_CAMPO')),
                ('id_Sequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQUENCIA')),
            ],
        ),
    ]
