# Generated by Django 3.0.3 on 2020-03-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0002_auto_20200326_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicao',
            name='sequencias',
            field=models.ManyToManyField(to='dinamica.SEQUENCIA'),
        ),
    ]
