# Generated by Django 3.0.3 on 2020-03-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0003_condicao_sequencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicao',
            name='value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
