# Generated by Django 3.0.3 on 2020-03-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0003_seq_aux'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHAVE_CONTAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_ChaveContas', models.CharField(max_length=10, unique=True)),
                ('Desc_ChaveContas', models.CharField(max_length=50)),
            ],
        ),
    ]
