# Generated by Django 3.0.3 on 2020-03-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0004_chave_contas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMADA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Camada', models.CharField(max_length=10, unique=True)),
                ('Nome_Camada', models.CharField(max_length=50)),
                ('TIPO_BASE_VENDAS', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TIPOVALOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_TipoValor', models.CharField(max_length=10)),
                ('Desc_TipoValor', models.CharField(max_length=50)),
            ],
        ),
    ]
