# Generated by Django 3.0.3 on 2020-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0004_condicao_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicao',
            name='value',
            field=models.TextField(),
        ),
    ]
