# Generated by Django 3.0.3 on 2020-03-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0005_auto_20200328_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicao',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
