# Generated by Django 3.0.3 on 2020-03-07 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0005_camada_tipovalor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovalor',
            name='Cod_TipoValor',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='CONDICAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Condicao', models.CharField(max_length=10, unique=True)),
                ('Desc_Condicao', models.CharField(max_length=50)),
                ('Escala_Qtde', models.IntegerField(max_length=1)),
                ('POS_NEG', models.CharField(max_length=1)),
                ('TIP_BASE_VENDAS', models.CharField(max_length=1)),
                ('MANDATORIA', models.IntegerField()),
                ('ESTATISTICA', models.IntegerField()),
                ('id_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CAMADA')),
                ('id_ChaveContas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CHAVE_CONTAS')),
                ('id_TipoValor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.TIPOVALOR')),
            ],
        ),
    ]
