# Generated by Django 3.0.3 on 2020-03-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0006_auto_20200307_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicao',
            name='Escala_Qtde',
            field=models.IntegerField(),
        ),
    ]
