# Generated by Django 3.0.3 on 2020-03-28 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0006_auto_20200328_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicao',
            name='sequencias',
        ),
        migrations.AddField(
            model_name='condicao',
            name='sequencias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dinamica.SEQUENCIA'),
        ),
    ]
