# Generated by Django 3.0.3 on 2020-03-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0007_auto_20200307_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONDICAO_SEQUENCIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO')),
                ('id_Sequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.SEQUENCIA')),
            ],
        ),
    ]
