# Generated by Django 3.0.3 on 2020-03-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0007_auto_20200328_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicao',
            name='sequencias',
        ),
        migrations.AddField(
            model_name='condicao',
            name='sequencias',
            field=models.ManyToManyField(to='dinamica.SEQUENCIA'),
        ),
    ]
