# Generated by Django 3.0.3 on 2020-03-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0008_auto_20200328_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencia',
            name='Value',
            field=models.TextField(null=True),
        ),
    ]
