# Generated by Django 3.0.3 on 2020-03-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0008_condicao_sequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONDICAO_CAMADA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CAMADA')),
                ('id_Condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO')),
            ],
        ),
    ]
