# Generated by Django 3.0.3 on 2020-03-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0009_sequencia_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencia',
            name='Value',
        ),
    ]
