# Generated by Django 3.0.3 on 2020-03-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0009_condicao_camada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANAL_VENDAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Vendas', models.CharField(max_length=10)),
                ('Desc_Vendas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LINHA_NEGOCIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_LinhaNegocio', models.CharField(max_length=10)),
                ('Desc_LinhaNegocio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ESQUEMA_DE_CALCULO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_CanalVendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CANAL_VENDAS')),
                ('id_LinhaNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.LINHA_NEGOCIO')),
            ],
        ),
    ]
