# Generated by Django 3.0.3 on 2020-03-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0010_canal_vendas_esquema_de_calculo_linha_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRECO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chave', models.IntegerField()),
                ('Data', models.DateTimeField()),
                ('Valor', models.FloatField()),
                ('Tipo_Base_Venda', models.CharField(max_length=1)),
                ('id_Esquema_Calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESQUEMA_DE_CALCULO')),
            ],
        ),
        migrations.CreateModel(
            name='CAMADA_ESQUEMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Condicao_Camada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CONDICAO_CAMADA')),
                ('id_Esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.ESQUEMA_DE_CALCULO')),
            ],
        ),
    ]
