# Generated by Django 3.0.4 on 2020-03-31 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamica', '0011_sequencia_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicao',
            name='Cod_Camada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamica.CAMADA'),
        ),
    ]
