# Generated by Django 3.0.4 on 2020-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numanomes', models.IntegerField()),
                ('codprd', models.IntegerField()),
                ('desprd', models.CharField(max_length=150)),
                ('codfilepd', models.IntegerField()),
                ('coddivfrn', models.IntegerField()),
                ('vlrprecosaldomesanterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlrprecocredito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlrprecodebito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlrmargemsaldomesanterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlrmargemcredito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vlrmargemdebito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
