# Generated by Django 3.0.4 on 2020-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMestre_ComposicaoPreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODPRD', models.IntegerField()),
                ('DESPRD', models.CharField(max_length=150)),
                ('ABC', models.CharField(max_length=1)),
                ('SENSIVEL_REBATE', models.SmallIntegerField()),
                ('TIPEDEREG', models.IntegerField()),
                ('CODEDEREG', models.IntegerField()),
                ('CODFILEMP', models.IntegerField()),
                ('CODFILFAT', models.IntegerField()),
                ('MB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MB_CALCULADA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VERBA_PRECO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FUND_PRECO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('REBATE', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ICMS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PIS_COFINS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DEVOLUCAO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TARGET', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FLEX', models.IntegerField()),
                ('CMV', models.DecimalField(decimal_places=3, max_digits=10)),
                ('BONIFICADO', models.DecimalField(decimal_places=3, max_digits=10)),
                ('COMPLEMENTO', models.DecimalField(decimal_places=3, max_digits=10)),
                ('PRECOBASE', models.DecimalField(decimal_places=3, max_digits=10)),
                ('DATA_PRECO', models.DateTimeField()),
                ('CODESTUNI', models.CharField(max_length=2)),
                ('PRECO_LIVRO', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DadosMestre_VerbaCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now=True)),
                ('csvfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='DadosMestreCSV',
            new_name='DadosMestre_ComposicaoPrecoCSV',
        ),
        migrations.RenameModel(
            old_name='DadosMestre',
            new_name='DadosMestre_Verba',
        ),
    ]
