# Generated by Django 3.0.4 on 2020-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CODFILEPD',
            field=models.IntegerField(),
        ),
    ]
