# Generated by Django 3.0.4 on 2020-03-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dadosmestrecsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='coddivfrn',
            new_name='CODDIVFRN',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='codfilepd',
            new_name='CODFILEPD',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='codprd',
            new_name='CODPRD',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='desprd',
            new_name='DESPRD',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='numanomes',
            new_name='NUMANOMES',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='vlrmargemcredito',
            new_name='VLRMARGEMCREDITO',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='vlrmargemdebito',
            new_name='VLRMARGEMDEBITO',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='vlrmargemsaldomesanterior',
            new_name='VLRMARGEMSALDOMESANTERIOR',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='vlrprecocredito',
            new_name='VLRPRECOCREDITO',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='vlrprecodebito',
            new_name='VLRPRECODEBITO',
        ),
        migrations.RenameField(
            model_name='dadosmestre',
            old_name='vlrprecosaldomesanterior',
            new_name='VLRPRECOSALDOMESANTERIOR',
        ),
    ]
