# Generated by Django 3.0.4 on 2020-04-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200405_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CODPRD',
            field=models.IntegerField(),
        ),
    ]
