# Generated by Django 3.0.4 on 2020-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200405_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='DATREF',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
