# Generated by Django 3.0.4 on 2020-03-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200309_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CMV',
            field=models.CharField(max_length=150),
        ),
    ]
