# Generated by Django 3.0.4 on 2020-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200305_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretrizesEstrategica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATINI', models.DateTimeField()),
                ('CODDRTCLLATU', models.IntegerField()),
                ('DESDRTCLLATU', models.CharField(max_length=150)),
                ('CODCLLCMPATU', models.IntegerField()),
                ('DESCLLCMPATU', models.CharField(max_length=150)),
                ('NOMFNCCPRATU', models.CharField(max_length=150)),
                ('CODGRPPRD', models.IntegerField()),
                ('DESGRPPRD', models.CharField(max_length=150)),
                ('CODCTGPRD', models.IntegerField()),
                ('DESCTGPRD', models.CharField(max_length=150)),
                ('CODSUBCTGPRD', models.IntegerField()),
                ('DESSUBCTGPRD', models.CharField(max_length=150)),
                ('CODGRPECOFRN', models.IntegerField()),
                ('NOMGRPECOFRN', models.CharField(max_length=150)),
                ('CODDIVFRN', models.IntegerField()),
                ('DESDIVFRN', models.CharField(max_length=150)),
                ('CODESTUNI', models.CharField(max_length=3)),
                ('NOMESTUNI', models.CharField(max_length=100)),
                ('VLRVNDFATLIQ', models.DecimalField(decimal_places=4, max_digits=10)),
                ('VLRMRGBRT', models.DecimalField(decimal_places=4, max_digits=10)),
                ('NOMREGGEO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiretrizesEstrategicaCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now=True)),
                ('csvfile', models.FileField(upload_to='')),
            ],
        ),
    ]
