# Generated by Django 3.0.4 on 2020-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200405_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CODFILEPD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
