# Generated by Django 3.0.4 on 2020-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diretrizesestrategica_diretrizesestrategicacsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='VLRMRGBRT',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='VLRVNDFATLIQ',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
