# Generated by Django 3.0.4 on 2020-03-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200309_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CMV',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
    ]
