# Generated by Django 3.0.4 on 2020-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200309_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODPRD', models.IntegerField()),
                ('CODFILEMP', models.IntegerField()),
                ('CODFILFAT', models.IntegerField()),
                ('DATA_PRECO', models.DateTimeField()),
                ('CODESTUNI', models.IntegerField()),
                ('META_VENDA_SUGERIDO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('META_VENDA_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PRECO_VENDA_LIQUIDO_SUGERIDO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PRECO_VENDA_LIQUIDO_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('COMPETITIVIDADE_SUGERIDO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('COMPETITIVIDADE_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PRECO_VENDA_BRUTA_SUGERIDO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PRECO_VENDA_BRUTA_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PRECO_BASE_SUGERIDO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('PRECO_BASE_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('REBATE_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('FUNDING_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VERBA_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('MARGEM_BRUTA_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('CMV_SUGERIDO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('CMV_PLANEJADO', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('SENSIVEL_REBATE', models.CharField(max_length=1)),
            ],
        ),
    ]
