# Generated by Django 3.0.4 on 2020-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200305_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='VLRMRGBRT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='VLRVNDFATLIQ',
            field=models.CharField(max_length=100),
        ),
    ]
