# Generated by Django 3.0.4 on 2020-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200405_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='VLRVNDFATLIQ',
            field=models.CharField(max_length=45),
        ),
    ]
