# Generated by Django 3.0.4 on 2020-03-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('CODCPRATU', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMCPRATU', models.CharField(max_length=45)),
                ('CODCLLCMPATU', models.IntegerField()),
                ('DESCLLCMPATU', models.CharField(max_length=45)),
                ('CODDRTCLLATU', models.IntegerField()),
                ('DESDRTCLLATU', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'COMPRADOR',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('CODDIVFRN', models.IntegerField(primary_key=True, serialize=False)),
                ('DESDIVFRN', models.CharField(max_length=45)),
                ('CODGRPECOFRN', models.IntegerField()),
                ('NOMGRPECOFRN', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'FORNECEDOR',
            },
        ),
        migrations.CreateModel(
            name='Mercadoria',
            fields=[
                ('CODPRD', models.IntegerField(primary_key=True, serialize=False)),
                ('DESPRD', models.CharField(max_length=45)),
                ('CODSML', models.IntegerField()),
                ('dessml', models.CharField(max_length=45)),
                ('ABC', models.CharField(max_length=1)),
                ('CODCPRATU', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Comprador')),
                ('CODDIVFRN', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Fornecedor')),
            ],
            options={
                'db_table': 'MERCADORIA',
            },
        ),
        migrations.CreateModel(
            name='RelacionamentoFilialRegiao',
            fields=[
                ('CODFILEPD', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMFILEPD', models.CharField(max_length=45)),
                ('CODFILFAT', models.IntegerField()),
                ('NOMFILFAT', models.CharField(max_length=45)),
                ('CODESTUNI', models.CharField(max_length=2)),
                ('NOMESTUNI', models.CharField(max_length=45)),
                ('TIPEDEREG', models.IntegerField()),
                ('CODEDEREG', models.IntegerField()),
            ],
            options={
                'db_table': 'RELACIONAMENTO_FILIAL_REGIAO',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('CODREPCMC', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMREPCMC', models.CharField(max_length=45)),
                ('DATCADREPCMC', models.DateTimeField()),
            ],
            options={
                'db_table': 'REPRESENTANTE',
            },
        ),
        migrations.CreateModel(
            name='TabAuxGrp',
            fields=[
                ('Id_Aux', models.IntegerField(primary_key=True, serialize=False)),
                ('CODSUBCTGPRD', models.IntegerField()),
                ('DESSUBCTGPRD', models.CharField(max_length=45)),
                ('CODCTGPRD', models.IntegerField()),
                ('DESCTGPRD', models.CharField(max_length=45)),
                ('CODGRPPRD', models.IntegerField()),
                ('DESGRPPRD', models.CharField(max_length=45)),
                ('Linha_de_negocio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TAB_AUX_GRP',
            },
        ),
        migrations.AddField(
            model_name='planocompras',
            name='SEMANA',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='dadosmestre_composicaopreco',
            table='COMPOSICAO_PRECO',
        ),
        migrations.AlterModelTable(
            name='dadosmestre_verba',
            table='VERBA_DISPONIVEL',
        ),
        migrations.AlterModelTable(
            name='diretrizesestrategica',
            table='DIRETRIZ_ESTRATEGICA',
        ),
        migrations.AlterModelTable(
            name='planocompras',
            table='PLANOCOMPRAS',
        ),
        migrations.CreateModel(
            name='VerbaeBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODFILFAT', models.IntegerField()),
                ('CODESTCLI', models.IntegerField()),
                ('NUMANOMESDIA', models.DateTimeField()),
                ('QUANTIDADE_ITENS_PEDIDO', models.IntegerField()),
                ('VALOR_TOTAL_VENDA_LIQUIDA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_UNITARIO_CMV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_TOTAL_CMV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_UNITARIO_FUNDING', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_TOTAL_FUNDING', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QUANTIDADE_ITENS_PROMOCAO', models.IntegerField()),
                ('QUANTIDADE_ITENS_BENEFICIO', models.IntegerField()),
                ('VALOR_UNITARIO_PROMOCAO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_UNITARIO_BENEFICIO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_UNITARIO_FUNDING_PRECO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_UNITARIO_FUNDING_MARGEM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_TOTAL_PROMOCAO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_TOTAL_BENEFICIO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_TOTAL_FUNDING_PRECO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_TOTAL_FUNDING_MARGEM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_TOTAL_DMS_SANSUNG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('REBATE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CODFILEPD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao')),
                ('CODPRD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria')),
            ],
            options={
                'db_table': 'VERBA_E_BC',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODFILFAT', models.IntegerField()),
                ('CODESTCLI', models.IntegerField()),
                ('NUMPED', models.IntegerField()),
                ('NUMANOMESSMN', models.DateTimeField()),
                ('NUMANOMESDIA', models.DateTimeField()),
                ('CMV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QDEITE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLRVNDLIQ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MARGEM_CONTRIBUICAO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MARGEM_BRUTA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLRRCTLIQ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLRIMPTOT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TRANSFERENCIA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DISTRIBUICAO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ARMAZENAGEM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FUNDING', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLRSUPFLX', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLRDSCFLXCNS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Despesas_Financeiras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Margem_por_Segmento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CODFILEPD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao')),
                ('CODPRD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria')),
                ('CODREPCMC', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Representante')),
            ],
            options={
                'db_table': 'VENDAS',
            },
        ),
        migrations.CreateModel(
            name='Otimizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_PRECO', models.DateTimeField()),
                ('CODFILFAT', models.IntegerField()),
                ('CODESTUNI', models.IntegerField()),
                ('VERBA_OTIMIZADA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VERBA_INPUT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VERBA_NECESSARIA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VERBA_DISPONIVEL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CODFILEMP', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao')),
                ('CODPRD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria')),
            ],
            options={
                'db_table': 'OTIMIZADOR',
            },
        ),
        migrations.AddField(
            model_name='mercadoria',
            name='CODFIL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao'),
        ),
        migrations.AddField(
            model_name='mercadoria',
            name='Id_Aux',
            field=models.ManyToManyField(to='api.TabAuxGrp'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATINI', models.DateTimeField()),
                ('NUMSMNANO', models.DateTimeField()),
                ('NOMSMSANO', models.DateTimeField()),
                ('NOMDIASMN', models.DateTimeField()),
                ('NUMDIASMN', models.DateTimeField()),
                ('NOMABVMESANO', models.CharField(max_length=45)),
                ('VLRUNTCSTSCO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QDEITEETQ', models.IntegerField()),
                ('VLRVNDPDAFLTETQ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QDEMEDVNDMNSMER', models.IntegerField()),
                ('VLRCSTCMPIDL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLRMEDPCOCMP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CODSTAPRDETQ', models.IntegerField()),
                ('DESSTAPRDETQ', models.CharField(max_length=45)),
                ('CODUNDREG', models.IntegerField()),
                ('DESUNDREG', models.CharField(max_length=45)),
                ('FLGUNDREG', models.CharField(max_length=45)),
                ('CODFIL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao')),
                ('CODPRD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria')),
            ],
            options={
                'db_table': 'ESTOQUE',
            },
        ),
        migrations.CreateModel(
            name='Elasticidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('Elasticidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qt', models.IntegerField()),
                ('pcmed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitfnd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verba', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codsml', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria')),
            ],
            options={
                'db_table': 'ELASTICIDADE',
            },
        ),
        migrations.CreateModel(
            name='Competitividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('NUMANOMES', models.DateTimeField()),
                ('NUMSMNANO', models.DateTimeField()),
                ('Id', models.IntegerField()),
                ('data_emissao', models.DateTimeField()),
                ('TipoPesquisa', models.CharField(max_length=45)),
                ('pc_mrt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pc_psq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pc_psq_pond', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pc_mrt_pond', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regiao', models.CharField(max_length=45)),
                ('Uf_Destino', models.CharField(max_length=2)),
                ('ABC', models.CharField(max_length=1)),
                ('CODPRD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria')),
            ],
            options={
                'db_table': 'COMPETITIVIDADE',
            },
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='Id_Aux',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='api.TabAuxGrp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CODFILEMP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao'),
        ),
        migrations.AlterField(
            model_name='dadosmestre_composicaopreco',
            name='CODPRD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria'),
        ),
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='CODFILEPD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao'),
        ),
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='CODPRD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria'),
        ),
        migrations.AlterField(
            model_name='planocompras',
            name='CODFILEMP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelacionamentoFilialRegiao'),
        ),
        migrations.AlterField(
            model_name='planocompras',
            name='CODPRD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Mercadoria'),
        ),
    ]
