# Generated by Django 3.0.4 on 2020-04-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200405_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='DATREFPOD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMMES',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMSMS',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
