# Generated by Django 3.0.4 on 2020-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200405_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMDIASMN',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='NOMSMSANO',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
