# Generated by Django 3.0.4 on 2020-04-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200405_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='CODUNDNGCCLI',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
