# Generated by Django 3.0.4 on 2020-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200405_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='CODSGMNGCCLI',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
