# Generated by Django 3.0.4 on 2020-04-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200405_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='CODFIL',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
