# Generated by Django 3.0.4 on 2020-04-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200405_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretrizesestrategica',
            name='VLRMRGCRB',
            field=models.CharField(max_length=45),
        ),
    ]
