# Generated by Django 3.0.4 on 2020-04-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200405_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='DATREF',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
