# Generated by Django 3.0.4 on 2020-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200405_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='VLRSLDPCOMESANT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
