# Generated by Django 3.0.4 on 2020-04-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200405_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='VLRCRDMRG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='VLRCRDPCO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='VLRDBTMRG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='VLRDBTPCO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='VLRSLDMRGMESANT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
