# Generated by Django 3.0.4 on 2020-04-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200405_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='otimizador',
            name='CODESTUNI',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRCMVCAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRCSTMERVND',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRMCDCAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRMCDOCD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRMRGBRTCAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRMRGBRTOCD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRMRGBRTRLZ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRPCOBSECAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRPCOBSEMER',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRPCOBSEOCD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRRCTLIQAPUCAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRRCTLIQAPUOCD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRRCTLIQAPURLZ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRVNDLIQCAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRVNDLIQOCD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otimizador',
            name='VLRVNDLIQRLZ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otimizador',
            name='VLRVBA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otimizador',
            name='VLRVBACAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otimizador',
            name='VLRVBADEM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otimizador',
            name='VLRVBADIS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otimizador',
            name='VLRVBAINP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='CODFILEPD',
            field=models.IntegerField(),
        ),
    ]
