# Generated by Django 3.0.4 on 2020-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200405_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmestre_verba',
            old_name='CODSMLPCO',
            new_name='NUMANOMES',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='CODESTUNI',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='CODFILEPD',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='CODFILFAT',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='CODPRD',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='CODREGPCO',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='DATREF',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='NUMRLCCIDGIR',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='TIPCALUTZPCOLIQ',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='TIPEDEREG',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRBNF',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRCPLCSTPCO',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRCSTCAL',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRDVL',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRFLXCNS',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRFND',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRFNDRBTITE',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRICM',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRMRGBRT',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRPCOBSEMER',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRPIS',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRUNTPCOALV',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_composicaopreco',
            name='VLRVBA',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='DATREF',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='VLRCRDMRG',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='VLRCRDPCO',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='VLRDBTMRG',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='VLRDBTPCO',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='VLRSLDMRGMESANT',
        ),
        migrations.RemoveField(
            model_name='dadosmestre_verba',
            name='VLRSLDPCOMESANT',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODCLLCMPATU',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODCLSMER',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODDIVFRN',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODESTUNI',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODFIL',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODFMLMER',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODGRPMER',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODSGMNGCCLI',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='CODUNDNGCCLI',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='DATREFPOD',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='DESCLSMER',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='DESDRTCLLATU',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='DESFMLMER',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='DESGRPMER',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='NOMCPR',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='NOMDIASMN',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='NOMMES',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='NOMSMS',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='NOMSMSANO',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='VLRMRGBRT',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='VLRMRGCRB',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='VLRRCTLIQAPU',
        ),
        migrations.RemoveField(
            model_name='diretrizesestrategica',
            name='VLRVNDFATLIQ',
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='abc',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='bonificado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='cmv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='codedereg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='codestuni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='codfilemp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='codfilfat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='codprd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='complemento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='data_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='desprd',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='devolucao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='flex',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='fund_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='mb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='mb_calculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='pis_cofins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='preco_livro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='precobase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='rebate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='sensivel_rebate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='tipedereg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_composicaopreco',
            name='verba_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='CODDIVFRN',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='DESPRD',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='VLRMARGEMCREDITO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='VLRMARGEMDEBITO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='VLRMARGEMSALDOMESANTERIOR',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='VLRPRECOCREDITO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='VLRPRECODEBITO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dadosmestre_verba',
            name='VLRPRECOSALDOMESANTERIOR',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='codcllcmpatu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='codctgprd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='coddivfrn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='coddrtcllatu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='codestuni',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='codgrpecofrn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='codgrpprd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='codsubctgprd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='datini',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='descllcmpatu',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='desctgprd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='desdivfrn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='desdrtcllatu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='desgrpprd',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='dessubctgprd',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='nomestuni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='nomfnccpratu',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='nomgrpecofrn',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='nomreggeo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='vlrmrgbrt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='vlrmrgcrb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='vlrrctliqapu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diretrizesestrategica',
            name='vlrvndfatliq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmestre_verba',
            name='CODPRD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
