# Generated by Django 3.0.4 on 2020-04-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200405_2313'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planocompras',
            table='mrt.MOVPLNCMPCAL',
        ),
    ]
