from django.contrib import admin
from . import models

admin.site.register(models.DadosMestre_Verba)
admin.site.register(models.DadosMestre_VerbaCSV)
admin.site.register(models.DadosMestre_ComposicaoPreco)
admin.site.register(models.DadosMestre_ComposicaoPrecoCSV)
admin.site.register(models.DiretrizesEstrategica)
admin.site.register(models.DiretrizesEstrategicaCSV)
admin.site.register(models.PlanoCompras)
admin.site.register(models.Otimizador)
admin.site.register(models.Fornecedor)
admin.site.register(models.Comprador)
admin.site.register(models.Mercadoria)
admin.site.register(models.TabAuxGrp)
admin.site.register(models.RelacionamentoFilialRegiao)
admin.site.register(models.Representante)
admin.site.register(models.Vendas)
admin.site.register(models.VerbaeBC)
admin.site.register(models.Elasticidade)
admin.site.register(models.Estoque)
admin.site.register(models.Competitividade)
